import {activeWorkspace} from "@/lib/data/teams";
import {loadSamples} from "@/lib/actions/auth";
import Link from "next/link";
import {metrics} from "@/lib/metrics";
import {money,type Dataset} from "@/lib/types";
import {LiveRefresh} from "./live-refresh";
export async function Dashboard({data,campaign=""}:{data:Dataset;campaign?:string}){
 const m=metrics(data,campaign);
 const teamId=await activeWorkspace();
 return <>{!data.campaigns.length&&<section className="panel"><h2>Your workspace is ready</h2><p>{teamId?"Start by creating a campaign and registering members.":"Create a campaign to get started, or load example records to explore the full workflow."}</p>{!teamId&&<form action={loadSamples}><button className="secondary">Load sample data</button></form>}</section>}<section className="hero-card"><div><p className="eyebrow">MAKE EVERY VISIT MATTER</p><h2>Your next loyal customer<br/>starts with one receipt.</h2><p>Register a member, capture their purchase, and give something back.</p><Link className="button" href="/members">Register a member ↗</Link><Link className="text-link" href="/redemptions">Redeem a gift →</Link></div><div className="hero-mark" aria-hidden>◈</div></section>
 <div className="section-bar"><form className="filter dashboard-filter"><label>Campaign overview<select name="campaign" defaultValue={campaign}><option value="">All campaigns</option>{data.campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="secondary">Apply filter</button></form><LiveRefresh/></div>
 <section className="metrics">{[{label:"Total sales",value:money(m.sales),note:`${m.receiptCount} receipts submitted`},{label:"Average order value",value:m.aov===null?"N/A":money(m.aov),note:"Sales ÷ number of receipts"},{label:"Completed redemptions",value:String(m.completed.length),note:"Gifts successfully claimed"},{label:"New members",value:String(m.newMembers),note:`${m.members.length} members in ${campaign?"this campaign":"your workspace"}`}].map(k=><article className="metric" key={k.label}><p>{k.label}</p><strong>{k.value}</strong><small>{k.note}</small><span>↗</span></article>)}</section>
 <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><h2>Member community</h2><span>{m.members.length} members</span></div><p className="caption">Gender split{campaign?" among campaign participants":""}</p><div className="gender-chart">{m.genders.map((g,i)=><div className="bar-row" key={g.name}><span>{g.name}</span><div className="bar-track"><div style={{width:`${m.members.length?g.count/m.members.length*100:0}%`,background:["#4e7458","#a6bc89","#d9b981","#d4dacf"][i]}}/></div><strong>{g.count}</strong><small>{m.members.length?Math.round(g.count/m.members.length*100):0}%</small></div>)}</div><div className="lifecycle">{m.lifecycle.map(l=><div key={l.name}><strong>{l.count}</strong><span>{l.name}</span></div>)}</div></section>
 <section className="panel"><div className="panel-heading"><h2>Gift inventory</h2><Link href="/gifts">Manage ↗</Link></div><p className="caption">{m.gifts.reduce((s,g)=>s+Number(g.stock),0)} gifts available · {m.gifts.filter(g=>Number(g.stock)<=5).length} need attention</p>{m.gifts.slice(0,5).map(g=><div className="inventory-row" key={g.id}><span className="gift-symbol">◇</span><div><strong>{g.name}</strong><small>{money(Number(g.threshold_amount))} minimum spend</small></div><span className={Number(g.stock)<=5?"badge warning":"badge"}>{g.stock} left</span></div>)}{!m.gifts.length&&<p className="caption">No gifts yet. Add your first reward in Gifts.</p>}</section></div>
 <section className="panel"><div className="panel-heading"><h2>Top members by average order value</h2><Link href="/members">View members ↗</Link></div><p className="caption">Ranked using {campaign?'this campaign’s':'all recorded'} receipts.</p>{m.rankings.slice(0,5).map((member,i)=><div className="activity-row" key={member.id}><span className="rank">{i+1}</span><div><strong>{member.name}</strong><small>{member.orders} receipts · {money(member.total)} total spend</small></div><strong>{money(member.aov)}</strong></div>)}{!m.rankings.length&&<p className="caption">Submit a receipt to see member rankings.</p>}</section><section className="panel"><div className="panel-heading"><h2>Recent redemptions</h2><Link href="/redemptions">View all ↗</Link></div>{m.completed.slice(0,5).map(r=><div className="activity-row" key={r.id}><span className="activity-dot"/><div><strong>{data.memberships.find(x=>x.id===r.member_id)?.name}</strong><small>{data.gifts.find(x=>x.id===r.gift_id)?.name}</small></div><span>{r.created_at.slice(0,10)}</span><span className="badge">Completed</span></div>)}{!m.completed.length&&<p className="caption">No redemptions yet. Register a member, submit a receipt, and redeem a qualifying gift.</p>}</section></>;
}
