"use client";
import {useActionState,useState} from "react";
import Link from "next/link";
import {teamAction,type TeamResult} from "@/lib/actions/teams";
import type {Team,Teammate,Invite} from "@/lib/data/teams";
import styles from "./team-workspace.module.css";
function TeamForm({operation,workspace,children,confirm}:{operation:string;workspace?:string;children:React.ReactNode;confirm?:string}){
 const [state,action,pending]=useActionState(teamAction,{ok:false,message:""} as TeamResult);const [copied,setCopied]=useState(false);
 return <form action={action} className={styles.form} onSubmit={e=>{if(confirm&&!window.confirm(confirm))e.preventDefault();}}><input type="hidden" name="operation" value={operation}/>{operation!=="switch"&&<input type="hidden" name="workspace" value={workspace??""}/>}<fieldset disabled={pending}>{children}</fieldset>{pending&&<p role="status">Saving…</p>}{state.message&&<p role="status" className={state.ok?"success":"notice"}>{state.message}</p>}{state.inviteUrl&&<div className={styles.inviteLink}><label>Private invitation link<input readOnly value={state.inviteUrl} onFocus={e=>e.target.select()}/></label><button type="button" className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(state.inviteUrl!);setCopied(true);}catch{setCopied(false);}}}>{copied?"Copied":"Copy link"}</button><p className="caption">Only the invited email can accept. This link is shown once; create a replacement if you lose it.</p></div>}</form>;
}
export function TeamWorkspace({teams,current,selected,people,invites,userId,email,canUseTeams,invitation}:{teams:Team[];current:Team|null;selected:string|null;people:Teammate[];invites:Invite[];userId:string;email:string;canUseTeams:boolean;invitation:string}){
 return <div className={styles.page}><header><p className="eyebrow">WORK BETTER TOGETHER</p><h1>Team workspace</h1><p>Share campaign work with your team. Your personal records stay private.</p></header><section className={styles.card}><h2>Current workspace</h2><p className={styles.current}>{current?current.name:"Personal workspace"} <span className="badge">{current?current.role:"Only you"}</span></p>{selected&&!current&&<p role="alert" className="notice">Your previous team is unavailable. Select Personal workspace to continue.</p>}<TeamForm operation="switch"><label>Switch workspace<select name="workspace" defaultValue={current?.id??""}><option value="">Personal workspace</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name} · {t.role}</option>)}</select></label><button>Use this workspace</button></TeamForm><Link href="/">Open dashboard →</Link></section>
 {!canUseTeams?<section className={styles.card}><h2>Use a confirmed email account</h2><p>Team access is tied to your email. Sign out of the demo and create or sign in to a confirmed email account to create or join a team.</p></section>:<div className={styles.grid}><section className={styles.card}><h2>Create a team</h2><p>Start an empty shared workspace for campaigns, receipts and rewards.</p><TeamForm operation="create"><label>Team name<input name="name" required maxLength={100} placeholder="Marketing & Loyalty"/></label><button>Create team</button></TeamForm></section><section className={styles.card}><h2>Join a team</h2><p>Signed in as <strong>{email}</strong>. Invitations must be addressed to this email.</p><TeamForm operation="join"><label>Invitation code<input name="token" required minLength={64} maxLength={64} defaultValue={invitation} autoComplete="off" placeholder="Paste the code from your invitation link"/></label><button>Accept invitation and join</button></TeamForm></section></div>}
 {current&&<><section className={styles.card}><h2>People in {current.name}</h2><p className="caption">Everyone can manage loyalty records. Owners manage roles and admins; admins invite and remove staff. Personal workspaces are never shared.</p><ul className={styles.people}>{people.map(person=><li key={person.user_id}><div><strong>{person.email}{person.user_id===userId?" (you)":""}</strong><span className="badge">{person.role}</span></div>{person.role!=="owner"&&<div className={styles.controls}>{current.role==="owner"&&<TeamForm operation="role" workspace={current.id}><input type="hidden" name="user" value={person.user_id}/><label>Role for {person.email}<select name="role" defaultValue={person.role}><option value="staff">Staff</option><option value="admin">Admin</option></select></label><button className="secondary">Save role</button></TeamForm>}{(current.role==="owner"||(current.role==="admin"&&person.role==="staff")||person.user_id===userId)&&<TeamForm operation="remove" workspace={current.id} confirm={person.user_id===userId?"Leave this team? You will lose access to its shared records.":`Remove ${person.email} from this team? Their access will end immediately.`}><input type="hidden" name="user" value={person.user_id}/><button className="secondary">{person.user_id===userId?"Leave team":"Remove"}</button></TeamForm>}</div>}</li>)}</ul></section>{current.role!=="staff"&&<section className={styles.card}><h2>Invite a teammate</h2><p>Create a private link for a named recipient. You can copy and share it yourself; no email is sent automatically.</p><TeamForm operation="invite" workspace={current.id}><label>Teammate email<input name="email" type="email" required maxLength={254}/></label><label>Role<select name="role"><option value="staff">Staff — manage loyalty records</option>{current.role==="owner"&&<option value="admin">Admin — also manage staff invitations</option>}</select></label><button>Create invitation</button></TeamForm>{invites.length>0&&<><h3>Invitations</h3><ul className={styles.people}>{invites.map(i=>{const status=i.used_at?"Accepted":i.revoked_at?"Revoked":new Date(i.expires_at).getTime()<Date.now()?"Expired":"Pending";return <li key={i.id}><div><strong>{i.email}</strong><span>{i.role} · {status}</span><span className="caption">Expires {new Date(i.expires_at).toLocaleDateString()}</span></div>{status==="Pending"&&(current.role==="owner"||i.role==="staff")&&<TeamForm operation="revoke" workspace={current.id} confirm="Revoke this invitation? The link will stop working."><input name="invite" type="hidden" value={i.id}/><button className="secondary">Revoke</button></TeamForm>}</li>;})}</ul></>}</section>}</>}
 </div>;
}
